namespace MDR_Importer;

public class FieldLists
{
    public Dictionary<string, string> addStudyFields { get; } = new() 
    {
        { "studies", @"sd_sid, display_title, 
        title_lang_code, brief_description, data_sharing_statement,
        study_start_year, study_start_month, study_type_id, 
        study_status_id, study_enrolment, study_gender_elig_id, min_age, 
        min_age_units_id, max_age, max_age_units_id, iec_level, datetime_of_data_fetch" },
        { "study_identifiers", @"sd_sid, identifier_value, identifier_type_id, 
        source_id, source, identifier_date, identifier_link" },
        { "study_titles", @"sd_sid, title_type_id, title_text, lang_code, lang_usage_id,
        is_default, comments" },
        { "study_references", @"sd_sid, pmid, citation, doi, type_id, comments" },
        { "study_people", @"sd_sid, contrib_type_id, person_given_name, 
        person_family_name, person_full_name, orcid_id, person_affiliation, organisation_id, 
        organisation_name" },
        { "study_organisations", @"sd_sid, contrib_type_id, organisation_id, 
        organisation_name" },
        { "study_topics", @"sd_sid, topic_type_id, original_value, original_ct_type_id, 
        original_ct_code, mesh_code, mesh_value" },
        { "study_relationships", @"sd_sid, relationship_type_id, target_sd_sid" },
        { "study_features", @"sd_sid, feature_type_id, feature_value_id" },
        { "study_links", @"sd_sid, link_label, link_url" },
        { "study_countries", @"sd_sid, country_id, country_name, status_id" },
        { "study_locations", @"sd_sid, facility_org_id, facility,  
        city_id, city_name, country_id, country_name, status_id" },
        { "study_ipd_available", @"sd_sid, ipd_id, ipd_type, ipd_url, ipd_comment" },
        { "study_conditions", @"sd_sid, original_value, original_ct_type_id, original_ct_code, 
        icd_code, icd_name" },
        { "study_iec", @"sd_sid, seq_num, iec_type_id, split_type, leader, indent_level,
          sequence_string, iec_text" }
    };
    
    
    public Dictionary<string, string> addStudyFields_insert { get; } = new() 
    {
        { "studies", @"s.sd_sid, display_title, 
        title_lang_code, brief_description, data_sharing_statement,
        study_start_year, study_start_month, study_type_id, 
        study_status_id, study_enrolment, study_gender_elig_id, min_age, 
        min_age_units_id, max_age, max_age_units_id, iec_level, datetime_of_data_fetch" },
        { "study_identifiers", @"s.sd_sid, identifier_value, identifier_type_id, 
        source_id, source, identifier_date, identifier_link" },
        { "study_titles", @"s.sd_sid, title_type_id, title_text, lang_code, lang_usage_id,
        is_default, comments" },
        { "study_references", @"s.sd_sid, pmid, citation, doi, type_id, comments" },
        { "study_people", @"s.sd_sid, contrib_type_id, person_given_name, 
        person_family_name, person_full_name, orcid_id, person_affiliation, organisation_id, 
        organisation_name" },
        { "study_organisations", @"s.sd_sid, contrib_type_id, organisation_id, 
        organisation_name" },
        { "study_topics", @"s.sd_sid, topic_type_id, original_value, original_ct_type_id, 
        original_ct_code, mesh_code, mesh_value" },
        { "study_relationships", @"s.sd_sid, relationship_type_id, target_sd_sid" },
        { "study_features", @"s.sd_sid, feature_type_id, feature_value_id" },
        { "study_links", @"s.sd_sid, link_label, link_url" },
        { "study_countries", @"s.sd_sid, country_id, country_name, status_id" },
        { "study_locations", @"s.sd_sid, facility_org_id, facility,  
        city_id, city_name, country_id, country_name, status_id" },
        { "study_ipd_available", @"s.sd_sid, ipd_id, ipd_type, ipd_url, ipd_comment" },
        { "study_conditions", @"s.sd_sid, original_value, original_ct_type_id, original_ct_code, 
        icd_code, icd_name" },
        { "study_iec", @"s.sd_sid, seq_num, iec_type_id, split_type, leader, indent_level,
          sequence_string, iec_text" }
    };
    
    public Dictionary<string, string> addObjectFields { get; } = new() 
    {
        { "data_objects", @"sd_oid, sd_sid, 
        title, version, display_title, doi, doi_status_id, publication_year,
        object_class_id, object_type_id, managing_org_id, managing_org, 
        lang_code, access_type_id, access_details, access_details_url, url_last_checked, 
        eosc_category, add_study_contribs, add_study_topics, datetime_of_data_fetch" },
        {"object_datasets", @"sd_oid, record_keys_type_id, record_keys_details, 
        deident_type_id, deident_direct, deident_hipaa,
        deident_dates, deident_nonarr, deident_kanon, deident_details,
        consent_type_id, consent_noncommercial, consent_geog_restrict,
        consent_research_type, consent_genetic_only, consent_no_methods, consent_details" },
        { "object_instances", @"sd_oid, system_id, system,
        url, url_accessible, url_last_checked, resource_type_id,
        resource_size, resource_size_units, resource_comments" },
        { "object_titles", @"sd_oid, title_type_id, title_text, lang_code,
        lang_usage_id, is_default, comments" },
        { "object_dates", @"sd_oid, date_type_id, date_is_range, date_as_string, start_year, 
        start_month, start_day, end_year, end_month, end_day, details" },
        { "object_people", @"sd_oid, contrib_type_id, person_given_name, 
        person_family_name, person_full_name, orcid_id, person_affiliation, organisation_id, 
        organisation_name" },
        { "object_organisations", @"sd_oid, contrib_type_id, organisation_id, 
        organisation_name" },
        { "object_topics", @"sd_oid, topic_type_id, original_value, original_ct_type_id,
        original_ct_code, mesh_code, mesh_value" },
        { "object_comments", @"sd_oid, ref_type, ref_source, pmid, pmid_version, notes" },
        { "object_descriptions", @"sd_oid, description_type_id, label, description_text, lang_code" },
        { "object_identifiers", @"sd_oid, identifier_value, identifier_type_id, 
        source_id, source, identifier_date" },
        { "object_db_links", @"sd_oid, db_sequence, db_name, id_in_db" },
        { "object_publication_types", @"sd_oid, type_name" },
        { "object_rights", @"sd_oid, rights_name, rights_uri, comments" },
        { "object_relationships", @"sd_oid, relationship_type_id, target_sd_oid" },
        { "journal_details", @"sd_oid, journal_title, pissn, eissn, journal_nlm_id, journal_iso_abbrev"}
    };
    
    public Dictionary<string, string> addObjectFields_insert { get; } = new() 
    {
        { "data_objects", @"s.sd_oid, sd_sid, 
        trim(title), version, trim(display_title), doi, doi_status_id, publication_year,
        object_class_id, object_type_id, managing_org_id, managing_org, 
        lang_code, access_type_id, access_details, access_details_url, url_last_checked, 
        eosc_category, add_study_contribs, add_study_topics, datetime_of_data_fetch" },
        {"object_datasets", @"s.sd_oid, record_keys_type_id, record_keys_details, 
        deident_type_id, deident_direct, deident_hipaa,
        deident_dates, deident_nonarr, deident_kanon, deident_details,
        consent_type_id, consent_noncommercial, consent_geog_restrict,
        consent_research_type, consent_genetic_only, consent_no_methods, consent_details" },
        { "object_instances", @"s.sd_oid, system_id, system,
        url, url_accessible, url_last_checked, resource_type_id,
        resource_size, resource_size_units, resource_comments" },
        { "object_titles", @"s.sd_oid, title_type_id, title_text, lang_code,
        lang_usage_id, is_default, comments" },
        { "object_dates", @"s.sd_oid, date_type_id, date_is_range, date_as_string, start_year, 
        start_month, start_day, end_year, end_month, end_day, details" },
        { "object_people", @"s.sd_oid, contrib_type_id, person_given_name, 
        person_family_name, person_full_name, orcid_id, person_affiliation, organisation_id, 
        organisation_name" },
        { "object_organisations", @"s.sd_oid, contrib_type_id, organisation_id, 
        organisation_name" },
        { "object_topics", @"s.sd_oid, topic_type_id, original_value, original_ct_type_id,
        original_ct_code, mesh_code, mesh_value" },
        { "object_comments", @"s.sd_oid, ref_type, ref_source, pmid, pmid_version, notes" },
        { "object_descriptions", @"s.sd_oid, description_type_id, label, description_text, lang_code" },
        { "object_identifiers", @"s.sd_oid, identifier_value, identifier_type_id, 
        source_id, source, identifier_date" },
        { "object_db_links", @"s.sd_oid, db_sequence, db_name, id_in_db" },
        { "object_publication_types", @"s.sd_oid, type_name" },
        { "object_rights", @"s.sd_oid, rights_name, rights_uri, comments" },
        { "object_relationships", @"s.sd_oid, relationship_type_id, target_sd_oid" },
        { "journal_details", @"s.sd_oid, journal_title, pissn, eissn, journal_nlm_id, journal_iso_abbrev"}
    };
    
    public Dictionary<string, string> delStudyFields { get; } = new() 
    {
        { "studies", @"sd_sid, display_title, 
        title_lang_code, brief_description, data_sharing_statement,
        study_start_year, study_start_month, study_type_id, 
        study_status_id, study_enrolment, study_gender_elig_id, min_age, 
        min_age_units_id, max_age, max_age_units_id, iec_level, datetime_of_data_fetch, added_on" },
        { "study_identifiers", @"sd_sid, identifier_value, identifier_type_id, 
        source_id, source, source_ror_id, identifier_date, identifier_link, added_on, coded_on" },
        { "study_titles", @"sd_sid, title_type_id, title_text, lang_code, lang_usage_id,
        is_default, comments, added_on" },
        { "study_references", @"sd_sid, pmid, citation, doi, type_id, comments, added_on" },
        { "study_people", @"sd_sid, contrib_type_id, person_given_name, 
        person_family_name, person_full_name, orcid_id, person_affiliation, organisation_id, 
        organisation_name, organisation_ror_id, added_on, coded_on" },
        { "study_organisations", @"sd_sid, contrib_type_id, organisation_id, 
        organisation_name, organisation_ror_id, added_on, coded_on" },
        { "study_topics", @"sd_sid, topic_type_id, original_value, original_ct_type_id, 
        original_ct_code, mesh_code, mesh_value, added_on, coded_on" },
        { "study_relationships", @"sd_sid, relationship_type_id, target_sd_sid, added_on" },
        { "study_features", @"sd_sid, feature_type_id, feature_value_id, added_on" },
        { "study_links", @"sd_sid, link_label, link_url, added_on" },
        { "study_countries", @"sd_sid, country_id, country_name, status_id, added_on, coded_on" },
        { "study_locations", @"sd_sid, facility_org_id, facility, facility_ror_id, 
        city_id, city_name, country_id, country_name, status_id, added_on, coded_on" },
        { "study_ipd_available", @"sd_sid, ipd_id, ipd_type, ipd_url, ipd_comment, added_on" },
        { "study_conditions", @"sd_sid, original_value, original_ct_type_id, original_ct_code, 
        icd_code, icd_name, added_on, coded_on" },
        { "study_iec", @"sd_sid, seq_num, iec_type_id, split_type, leader, indent_level, 
        sequence_string, iec_text, iec_class_id, iec_class, iec_parsed_text, added_on, coded_on" }
    };
    
    public Dictionary<string, string> delObjectFields { get; } = new() 
    {
        { "data_objects", @"sd_oid, sd_sid, 
        title, version, display_title, doi, doi_status_id, publication_year,
        object_class_id, object_type_id, 
        managing_org_id, managing_org, managing_org_ror_id, lang_code, access_type_id,
        access_details, access_details_url, url_last_checked, eosc_category, add_study_contribs,
        add_study_topics, datetime_of_data_fetch, added_on, coded_on" },
        { "object_datasets", @"sd_oid, record_keys_type_id, record_keys_details, 
        deident_type_id, deident_direct, deident_hipaa,
        deident_dates, deident_nonarr, deident_kanon, deident_details,
        consent_type_id, consent_noncommercial, consent_geog_restrict,
        consent_research_type, consent_genetic_only, consent_no_methods, consent_details, added_on" },
        { "object_instances", @"sd_oid, system_id, system,
        url, url_accessible, url_last_checked, resource_type_id,
        resource_size, resource_size_units, resource_comments, added_on, coded_on " },
        { "object_titles", @"sd_oid, title_type_id, title_text, lang_code,
        lang_usage_id, is_default, comments, added_on" },
        { "object_dates", @"sd_oid, date_type_id, date_is_range, date_as_string, start_year, 
        start_month, start_day, end_year, end_month, end_day, details, added_on" },
        { "object_people", @"sd_oid, contrib_type_id, person_given_name, 
        person_family_name, person_full_name, orcid_id, person_affiliation, organisation_id, 
        organisation_name, organisation_ror_id, added_on, coded_on" },
        { "object_organisations", @"sd_oid, contrib_type_id, organisation_id, 
        organisation_name, organisation_ror_id, added_on, coded_on" },
        { "object_topics", @"sd_oid, topic_type_id, original_value, original_ct_type_id,
         original_ct_code, mesh_code, mesh_value, added_on, coded_on" },
        { "object_comments", @"sd_oid, ref_type, ref_source, pmid, pmid_version, notes, added_on" },
        { "object_descriptions", @"sd_oid, description_type_id, label, description_text, lang_code, added_on" },
        { "object_identifiers", @"sd_oid, identifier_value, identifier_type_id, 
        source_id, source, source_ror_id, identifier_date, added_on, coded_on" },
        { "object_db_links", @"sd_oid, db_sequence, db_name, id_in_db, added_on" },
        { "object_publication_types", @"sd_oid, type_name, added_on" },
        { "object_rights", @"sd_oid, rights_name, rights_uri, comments, added_on" },
        { "object_relationships", @"sd_oid, relationship_type_id, target_sd_oid, added_on" },
        { "journal_details", @"sd_oid, pissn, eissn, journal_title, publisher_id, 
        publisher, added_on, coded_on" }
    };

}